spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/save_money}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true

google:
  credentials:
    path: ${GOOGLE_CREDENTIALS_PATH:data/important/smsreceiver.json}
    json-content: ${GOOGLE_CREDENTIALS_JSON_CONTENT:""}

jwt:
  secret: ${JWT_SECRET:very-strong-secret-key-at-least-32-characters-long}
  access-token-expiration: 3600000 # 1시간 (ms)
  refresh-token-expiration: 604800000 # 7일 (ms)

logging:
  level:
    org.hibernate.SQL: debug
